# This file was generated by GoReleaser. DO NOT EDIT.
cask "jamshid" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "14251b31d5f20e1eb30757d4f9bdda8673dfb43e0bf0865697e13fef2fcf410f"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
    on_arm do
      sha256 "d43a10e5b9897a184e36fe30b91342e26ec7a941f5a81b87c209ce8b444930dd"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
  end

  on_linux do
    on_intel do
      sha256 "91f72df4c7116a9eaeb5354f580d82592f1601246f4b29e6cf2dc32013853827"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
    on_arm do
      sha256 "378d13b82e0251843a2ac17c401ff3428000e6e51eec08ef7af8600260715594"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
  end

  name "jamshid"
  desc "Jamshid is a CLI tool for managing multiple Claude Code profiles"
  homepage "https://github.com/PapaDanielVi/jamshid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jamshid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jamshid"]
    end
  end

  # No zap stanza required

end
