# This file was generated by GoReleaser. DO NOT EDIT.
cask "jamshid" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "228f6a2e5d4f622832b5521122e37cbef0edfb7f08cd9f57d567096bba799ce4"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5cba95fb8440dba47bcf676ce935e90599b49bee272d10f4ea2d91cf8ee37991"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2f6edb1811bc1cd9342a3f348d1c77f93fce2456b1bf5ae46c11622587551c16"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d9972614cd221b790a89c8a96a6e1571332b39952cfe01f83766043216649bc5"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Linux_x86_64.tar.gz"
    end
  end

  name "jamshid"
  desc "Jamshid is a CLI tool for managing multiple Claude Code profiles"
  homepage "https://github.com/PapaDanielVi/jamshid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jamshid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jamshid"]
    end
  end

  # No zap stanza required
end
