# This file was generated by GoReleaser. DO NOT EDIT.
cask "jamshid" do
  version "0.1.10"

  on_macos do
    on_intel do
      sha256 "d593802d0691afc69b4c8ecc17278bbe6bb900898e2e34ae3a06cb8d553ea6ed"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
    on_arm do
      sha256 "ef83e350bc580e6af59d113bfcf65750dba85ad45c9800e4adbb6f7b86b5ad20"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
  end

  on_linux do
    on_intel do
      sha256 "68890076c7c517176d416067fc90aae17d408797e0ca308628ade2fd32fd0675"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
    on_arm do
      sha256 "182f44744f7db07ba69bbf6e597fc5aafcec9e10f6a73399e0298cc6d4c6248a"
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v#{version}/jamshid_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/jamshid"
    end
  end

  name "jamshid"
  desc "Jamshid is a CLI tool for managing multiple Claude Code profiles"
  homepage "https://github.com/PapaDanielVi/jamshid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jamshid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jamshid"]
    end
  end

  # No zap stanza required

end
