# This file was generated by GoReleaser. DO NOT EDIT.
cask "neo4j-exporter" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "dada126e842bfc16cc8c6950625dd2a0a789762dabd2b0d9eb66cc2163ae41af"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
    on_arm do
      sha256 "cc4508aa0d24302930a3bfa8b243cca331e86117c922dc65d1fab9699097b4c3"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
  end

  on_linux do
    on_intel do
      sha256 "43207d0ad4d21233347c5c3621bb15b8d31575a4108320585a6a03df5a9e1cdc"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
    on_arm do
      sha256 "746a30d2cfaff914f38f8d21f971dee2d5a3a2de16c1427a8f0454d911a7ccc6"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
  end

  name "neo4j-exporter"
  desc "Prometheus exporter for Neo4j graph databases."
  homepage "https://github.com/PapaDanielVi/neo4j-exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "neo4j-exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/neo4j-exporter"]
    end
  end

  # No zap stanza required

end
