# This file was generated by GoReleaser. DO NOT EDIT.
cask "neo4j-exporter" do
  version "0.0.24"

  on_macos do
    on_intel do
      sha256 "a6e585d39f3efc712df9ca4e31ff66efe02946494adcc2df9c9cba0e574c5a96"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
    on_arm do
      sha256 "c15338cbf08c6abc91e113e804dff19c1110a0ac3c8475c322327851808c0f20"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
  end

  on_linux do
    on_intel do
      sha256 "6ac604ada65ccf35afd9c8f27dcac9c885f8275fb1f893a735a7644b16ae29ff"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
    on_arm do
      sha256 "b5882525fcecd86098fb371cf97603a8da27c64f2dbdf79ce9ac43a7a342a343"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
  end

  name "neo4j-exporter"
  desc "Prometheus exporter for Neo4j graph databases."
  homepage "https://github.com/PapaDanielVi/neo4j-exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "neo4j-exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/neo4j-exporter"]
    end
  end

  # No zap stanza required

end
