# This file was generated by GoReleaser. DO NOT EDIT.
cask "neo4j-exporter" do
  version "0.0.26"

  on_macos do
    on_intel do
      sha256 "8493bb3f162d53dec8876e878bff7886685ad1efd4759ed84fda9cc281516e50"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
    on_arm do
      sha256 "cb7b0c8efa9defd99bc6cecd1e8c5ef299bc21a6e34fc2a362a9b48b8a9274d9"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
  end

  on_linux do
    on_intel do
      sha256 "be74b53905a07a03211426e8ffc70858798d0ec610fe0c83b00d27899c97d850"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
    on_arm do
      sha256 "7aae5b5519ae0a5c77e692962269d9e8fb888b282661edff089c70cf847277bf"
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v#{version}/neo4j-exporter_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/neo4j-exporter"
    end
  end

  name "neo4j-exporter"
  desc "Prometheus exporter for Neo4j graph databases."
  homepage "https://github.com/PapaDanielVi/neo4j-exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "neo4j-exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/neo4j-exporter"]
    end
  end

  # No zap stanza required

end
