# This file was generated by GoReleaser. DO NOT EDIT.
cask "ostrakon" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "064de70d95678c55738a37eff5e1deac00628056274d6724de596b836a52a373"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
    on_arm do
      sha256 "5cac90431404916be2e65e25159da7406e233f8bda6b76e9ddf906ae93e1f4d0"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a844693de0bd59b4ea52ad94d347c56f437b9eba5dea15e6bf58cc94c95f061"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
    on_arm do
      sha256 "394a1a0f9db5bd645262e964344ac9081a9704c14fc42baa83ca2f7b13840cec"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
  end

  name "ostrakon"
  desc "Ostrakon is a secure CLI tool for managing secrets in a private GitHub repository with client-side encryption."
  homepage "https://github.com/PapaDanielVi/ostrakon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ostrakon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ostrakon"]
    end
  end

  # No zap stanza required

end
