# This file was generated by the ostrakon release workflow. DO NOT EDIT.
cask "ostrakon" do
  version "0.1.15"

  on_macos do
    on_arm do
      sha256 "60f1002dbad8cf517369d6a8c1e3ada5505c0d546de8a3a49e537d85c3c0f4fe"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d10a40ea2d514c183662f5f7a7cbf3b3149bba394073aac3dc7afc15d4ff7f8c"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b637b28fdc926cc517ab5fb7921395499e2938739cff4c49d99775663b04796b"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0578ad022b61f5a9bf8e535720031a288276b7cf9e5a9cfe287a2061ecb1c728"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_x86_64.tar.gz"
    end
  end

  name "ostrakon"
  desc "Ostrakon is a secure CLI tool for managing secrets in a private GitHub repository with client-side encryption."
  homepage "https://github.com/PapaDanielVi/ostrakon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ostrakon"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ostrakon"]
    end
  end
end
