# This file was generated by GoReleaser. DO NOT EDIT.
cask "ostrakon" do
  version "0.1.12"

  on_macos do
    on_intel do
      sha256 "42c98e73a9dddf0d7def865fb92d1d9493e3a253391ebe12972f3e1efc10baea"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
    on_arm do
      sha256 "7b84834b4b06a8f68bee50126fe7c9a9daf49c320f3cc11027766045c51977cc"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d1da4666a0cd31aa5a9535103434f0f07a728f8d6dcdb19ccf2e022e5a8d3b2"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
    on_arm do
      sha256 "7f3b48025d86f57356fee3d04c4086c659100356871ddcdf1cbd606970a085c2"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/ostrakon"
    end
  end

  name "ostrakon"
  desc "Ostrakon is a secure CLI tool for managing secrets in a private GitHub repository with client-side encryption."
  homepage "https://github.com/PapaDanielVi/ostrakon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ostrakon"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ostrakon"]
    end
  end

  # No zap stanza required

end
