# This file was generated by GoReleaser. DO NOT EDIT.
cask "secret-shift" do
  version "0.1.12"

  on_macos do
    on_intel do
      sha256 "e479d74ea359a665c12b48b9bbb097d31efdf544ce1d4bd6c2da536beb7a65c5"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
    on_arm do
      sha256 "f417e27ebbbc0d3a31b2241c0ea5fb9cebf4dec8ff4e6d959c58fd1bf826d97a"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
  end

  on_linux do
    on_intel do
      sha256 "c31c9b93587a6d9a5e1bdae83f87b1437df5a71dd59d8b9ae2e5fa85f277dbb5"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
    on_arm do
      sha256 "02cb5de8b2f667615d71aaab95b14fa900e5a0f4ee30e6542ed65eabac03655b"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
  end

  name "secret-shift"
  desc "SecretShift is a CLI tool for migrating and syncing secrets and environment variables between providers"
  homepage "https://github.com/PapaDanielVi/secret-shift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secret-shift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/secret-shift"]
    end
  end

  # No zap stanza required

end
