# This file was generated by the secret-shift release workflow. DO NOT EDIT.
cask "secret-shift" do
  version "0.1.23"

  on_macos do
    on_arm do
      sha256 "4176910cd958a012ffd07b42a0e6e4eacd3a5e3da030e81666f0b1e96a22061f"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b527a4e23427d52275c73db538032cd5a623338d25889ce21bd45e5280fc080d"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "89a857ed25264ae4739515fc16c0749410d7b076301104e2a27b429f0b964a26"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3561f88a0ad319ca920d8cc1a5e137c7d620b1c9bef2e78ecba281af0511fcb8"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Linux_x86_64.tar.gz"
    end
  end

  name "secret-shift"
  desc "SecretShift is a CLI tool for migrating and syncing secrets and environment variables between providers"
  homepage "https://github.com/PapaDanielVi/secret-shift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secret-shift"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/secret-shift"]
    end
  end
end
