# This file was generated by GoReleaser. DO NOT EDIT.
cask "secret-shift" do
  version "0.1.16"

  on_macos do
    on_intel do
      sha256 "6b0f3e69f5d6f5ef3cb2f4f600a6b9ca21285342b9fc65ddb521ed0465d4fd7f"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Darwin_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
    on_arm do
      sha256 "f38b2b296eb83e82c8c0db38f371ef03c29644b59086f04335bded7e0d7378a1"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Darwin_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
  end

  on_linux do
    on_intel do
      sha256 "5a9b8a8abda5a9ccd5bbc43e42a5cb1e7e1eac3fcebcc6d05a0c842ceb3a96b9"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Linux_x86_64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
    on_arm do
      sha256 "2ffd20f5e66f69d150ced3bae0e850d8a12fa6faf237a9c4cea08a504ecec87c"
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v#{version}/secret-shift_Linux_arm64.tar.gz",
        verified: "https://github.com/PapaDanielVi/secret-shift"
    end
  end

  name "secret-shift"
  desc "SecretShift is a CLI tool for migrating and syncing secrets and environment variables between providers"
  homepage "https://github.com/PapaDanielVi/secret-shift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secret-shift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/secret-shift"]
    end
  end

  # No zap stanza required

end
