# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jamshid < Formula
  desc "Jamshid is a CLI tool for managing multiple Claude Code profiles"
  homepage "https://github.com/PapaDanielVi/jamshid"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.8/jamshid_Darwin_x86_64.tar.gz"
      sha256 "e02ada3d63c1bf2bd1f6472ad9501f7c16e59e45fd88b3653676d85b7c39d114"

      def install
        bin.install "jamshid"
      end
    end
    on_arm do
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.8/jamshid_Darwin_arm64.tar.gz"
      sha256 "d54c9e21ee66edf24248535a8649203e78e6118e240c1a7c508b53501e5864db"

      def install
        bin.install "jamshid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.8/jamshid_Linux_x86_64.tar.gz"
        sha256 "c8499fbbe3063e69b8628d042883591c71cbe6347070299ed3a49d02638fcf01"

        def install
          bin.install "jamshid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.8/jamshid_Linux_arm64.tar.gz"
        sha256 "480fe70a0837137326a4b0c1058520618118621322e0901f3c9dfce04d4f2329"

        def install
          bin.install "jamshid"
        end
      end
    end
  end

  test do
    system "#{bin}/jamshid --version"
  end
end
