# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jamshid < Formula
  desc "Jamshid is a CLI tool for managing multiple Claude Code profiles"
  homepage "https://github.com/PapaDanielVi/jamshid"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.6/jamshid_Darwin_x86_64.tar.gz"
      sha256 "52d97537b1d54a4d1a78931aed469c807f8a0a21664d638bf919566583b151d6"

      def install
        bin.install "jamshid"
      end
    end
    on_arm do
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.6/jamshid_Darwin_arm64.tar.gz"
      sha256 "96f775a209b25ccbb3a7ac84497415e179e9c1d912b1c50be9959f9ab7f2ec84"

      def install
        bin.install "jamshid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.6/jamshid_Linux_x86_64.tar.gz"
        sha256 "ec7a84829edaf3ca65baa7bce901c56e4102044c750b9cd7d841b30e320a58e9"

        def install
          bin.install "jamshid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.6/jamshid_Linux_arm64.tar.gz"
        sha256 "b376cd95e4ef054b40f2fb07c987ae9d356f862f75f8c0c6ec4dcf45e760c896"

        def install
          bin.install "jamshid"
        end
      end
    end
  end

  test do
    system "#{bin}/jamshid --version"
  end
end
