# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jamshid < Formula
  desc "Jamshid is a CLI tool for managing multiple Claude Code profiles"
  homepage "https://github.com/PapaDanielVi/jamshid"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.7/jamshid_Darwin_x86_64.tar.gz"
      sha256 "d9ac80526861da8a2f2e288a6913fd487f9e6641090cc84900ed50bc1b01cc94"

      def install
        bin.install "jamshid"
      end
    end
    on_arm do
      url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.7/jamshid_Darwin_arm64.tar.gz"
      sha256 "763a2c08f047bfb3cb727f396379835022e970c8f7c058b6c8deaba9a6f40dac"

      def install
        bin.install "jamshid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.7/jamshid_Linux_x86_64.tar.gz"
        sha256 "c92dba13ff378a34783e555579143c25773563ac69ad6a643252e019357aa472"

        def install
          bin.install "jamshid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PapaDanielVi/jamshid/releases/download/v0.1.7/jamshid_Linux_arm64.tar.gz"
        sha256 "7b9ffafffae032611a59308818fe90574c183addac5194ee1d2b71d7928018fd"

        def install
          bin.install "jamshid"
        end
      end
    end
  end

  test do
    system "#{bin}/jamshid --version"
  end
end
