# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neo4jExporter < Formula
  desc "Prometheus exporter for Neo4j graph databases."
  homepage "https://github.com/PapaDanielVi/neo4j-exporter"
  version "0.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v0.0.22/neo4j-exporter_Darwin_x86_64.tar.gz"
      sha256 "da7b8a00bb8586f58ae087266629903e9e1b9ac5adc2d73008db3702a8d1e449"

      define_method(:install) do
        bin.install "neo4j-exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v0.0.22/neo4j-exporter_Darwin_arm64.tar.gz"
      sha256 "0a080c80bba583616490e2c493c843e08746d60996aae097103d8274e36db713"

      define_method(:install) do
        bin.install "neo4j-exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v0.0.22/neo4j-exporter_Linux_x86_64.tar.gz"
      sha256 "39bfc43f002746dffd74ce928cc6a0399672684e70bf67163e7a13f8c85d34ab"
      define_method(:install) do
        bin.install "neo4j-exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/neo4j-exporter/releases/download/v0.0.22/neo4j-exporter_Linux_arm64.tar.gz"
      sha256 "8fcf8d840179159da4a58be07bfcb79f4b3bd438beac72b7f7d36d483e0a54c9"
      define_method(:install) do
        bin.install "neo4j-exporter"
      end
    end
  end

  test do
    system "#{bin}/neo4j-exporter --version"
  end
end
