# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ostrakon < Formula
  desc "Ostrakon is a secure CLI tool for managing secrets in a private GitHub repository with client-side encryption."
  homepage "https://github.com/PapaDanielVi/ostrakon"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v0.0.4/ostrakon_Darwin_x86_64.tar.gz"
      sha256 "bec4f0a5682ad01c58088dcf58876da55f9e1212dc05ec4519510d699f3854a4"

      define_method(:install) do
        bin.install "ostrakon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v0.0.4/ostrakon_Darwin_arm64.tar.gz"
      sha256 "5d003553799d6b40d1db3277319cd3986e3679704b795ca90e61ca04ec7ca17e"

      define_method(:install) do
        bin.install "ostrakon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v0.0.4/ostrakon_Linux_x86_64.tar.gz"
      sha256 "3d950751321e812a6bebb04a7b73c1a38bfc67c538c5a5a2232209229d81c460"
      define_method(:install) do
        bin.install "ostrakon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v0.0.4/ostrakon_Linux_arm64.tar.gz"
      sha256 "ddc4a1d6a38848290e92df71535b11ce52617870193c4480a3e3030aecf6dc4e"
      define_method(:install) do
        bin.install "ostrakon"
      end
    end
  end

  test do
    system "#{bin}/ostrakon --version"
  end
end
