# This file was generated by GoReleaser. DO NOT EDIT.
cask "ostrakon" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "1129fb7402381f26e939ac735597119363a66c21ce3b15eeff77beeacfa759da"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "169cbe5209127691de52e991494f421ac07e8b1a03f98f7ab608bf58d2c5fe0c"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "64504ad9ae8e4d9a213027c10ff4d4d44c2d5884317cb86b73f305785f2015a5"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "601474678ec6c5121b0ded5c6e9f73b58e92ebce90b1aa439b4873189bd2e4de"
      url "https://github.com/PapaDanielVi/ostrakon/releases/download/v#{version}/ostrakon_Linux_arm64.tar.gz"
    end
  end

  name "ostrakon"
  desc "Ostrakon is a secure CLI tool for managing secrets in a private GitHub repository with client-side encryption."
  homepage "https://github.com/PapaDanielVi/ostrakon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ostrakon"

  # No zap stanza required

end
