# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretShift < Formula
  desc "SecretShift is a CLI tool for migrating and syncing secrets and environment variables between providers"
  homepage "https://github.com/PapaDanielVi/secret-shift"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.9/secret-shift_Darwin_x86_64.tar.gz"
      sha256 "57014988470a835db76d8191634d85dd41470bcd92a390ae6b1249c2ac621be2"

      define_method(:install) do
        bin.install "secret-shift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.9/secret-shift_Darwin_arm64.tar.gz"
      sha256 "a01e59c408222f5cbc80dffb638f47de7a4b6de4329b4e5fd2ab7ead16ba424f"

      define_method(:install) do
        bin.install "secret-shift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.9/secret-shift_Linux_x86_64.tar.gz"
      sha256 "3d97275c768a4554069d03757c9446264eb98a1cc1898ede5897a075060ae73c"
      define_method(:install) do
        bin.install "secret-shift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.9/secret-shift_Linux_arm64.tar.gz"
      sha256 "0e5aac9560616ca3cbb3a1571acc56244d5ffae0305a14168a8c074ad5904b88"
      define_method(:install) do
        bin.install "secret-shift"
      end
    end
  end
end
