# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SecretShift < Formula
  desc "SecretShift is a CLI tool for migrating and syncing secrets and environment variables between providers"
  homepage "https://github.com/PapaDanielVi/secret-shift"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.6/secret-shift_Darwin_x86_64.tar.gz"
      sha256 "5c36b5a3c5d2c0059f6cc90daca3fe058bd3cbd0e95986763663bb2ffe379660"

      define_method(:install) do
        bin.install "secret-shift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.6/secret-shift_Darwin_arm64.tar.gz"
      sha256 "dd0422816ec6b3cb8dc27d02b0b425e69fd5cca7b8fda037b796d75d756d6922"

      define_method(:install) do
        bin.install "secret-shift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.6/secret-shift_Linux_x86_64.tar.gz"
      sha256 "c496ebe714498213bca09b4c40b31489330726b0fe3fadd517d047822683db4a"
      define_method(:install) do
        bin.install "secret-shift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PapaDanielVi/secret-shift/releases/download/v0.1.6/secret-shift_Linux_arm64.tar.gz"
      sha256 "c8d95ba7f85e51829e0ad807c2f954c4f2e37dc9c8f3a45681f481dda6a233a9"
      define_method(:install) do
        bin.install "secret-shift"
      end
    end
  end

  test do
    system "#{bin}/secret-shift --version"
  end
end
